# Generated by Django 2.2.6 on 2020-01-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irisapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='petal_length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='feature',
            name='petal_widtth',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='feature',
            name='sepel_length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='feature',
            name='sepel_width',
            field=models.FloatField(),
        ),
    ]
