# Generated by Django 3.0.3 on 2020-02-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irisapp', '0002_auto_20200115_1427'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Species',
            new_name='Speciess',
        ),
    ]
