# Generated by Django 3.0.3 on 2020-02-12 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irisapp', '0003_auto_20200212_2013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Speciess',
            new_name='Species',
        ),
    ]
